language: python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements-nocuda.txt

script:
  - python evoltier/test/make_test.py

#after_success:
#  - coveralls
#
#notifications:
#  slack:
#    secure: your_token_key